# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued', models.BooleanField(default=False)),
                ('issue_time', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('return_time', models.DateTimeField()),
                ('hash', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
