# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180120_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='return_time',
            field=models.DateTimeField(blank='True', null='True'),
        ),
    ]
