# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('books', '0002_auto_20170930_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDepartmentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='bookdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookdepartmentsubject',
            name='book',
            field=models.ManyToManyField(to='books.BookDescription'),
        ),
        migrations.AddField(
            model_name='bookdepartmentsubject',
            name='department',
            field=models.ManyToManyField(to='department.Department'),
        ),
        migrations.AddField(
            model_name='bookdepartmentsubject',
            name='subject',
            field=models.ManyToManyField(to='department.Subject'),
        ),
    ]
