# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170930_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='book',
        ),
        migrations.AddField(
            model_name='bookdepartmentsubject',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.BookDescription'),
        ),
    ]
