# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_semester'),
        ('books', '0004_auto_20171001_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='semester',
        ),
        migrations.AddField(
            model_name='bookdepartmentsubject',
            name='semester',
            field=models.ManyToManyField(to='department.Semester'),
        ),
    ]
