# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20171002_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='subject',
        ),
    ]
