# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180120_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdepartmentsubject',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookDepartmentSubject',
        ),
    ]
