# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20180120_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdescription',
            name='image_url',
            field=models.URLField(blank=True, default='{{book.image_url}}', null=True),
        ),
        migrations.AlterField(
            model_name='bookdescription',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='department.Subject'),
        ),
    ]
