# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180127_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdescription',
            name='subject',
            field=models.ManyToManyField(blank=True, to='department.Subject'),
        ),
    ]
