# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180127_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdescription',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='bookdescription',
            name='initial_stock',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookdescription',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookdescription',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
