# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.BigIntegerField()),
                ('branch', models.CharField(choices=[('cse', 'COMPUTER SCIENCE AND ENGINEERING'), ('et&t', 'ELECTRONICS AND TELECOMMUNICATIONS'), ('eee', 'ELECTRICAL AND ELCETRONICS ENGINEERING'), ('mech', 'MECHANICAL ENGINEERING'), ('civil', 'CIVIL ENGINEERING')], max_length=10)),
                ('sem', models.CharField(choices=[('1', '1st SEMESTER'), ('2', '2nd SEMESTER'), ('3', '3rd SEMESTER'), ('4', '4th SEMESTER'), ('5', '5th SEMESTER'), ('6', '6th SEMESTER'), ('7', '7th SEMESTER'), ('8', '8th SEMESTER')], max_length=1)),
                ('libcard', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('entity', models.CharField(choices=[('student', 'STUDENT'), ('librarian', 'LIBRARIAN'), ('faculty', 'FACULTY'), ('staff', 'STAFF')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='staff',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
