# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170928_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entity',
            field=models.CharField(choices=[('student', 'STUDENT'), ('librarian', 'LIBRARIAN'), ('faculty', 'FACULTY'), ('staff', 'STAFF')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
