# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170928_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('cse', 'COMPUTER SCIENCE AND ENGINEERING'), ('et&t', 'ELECTRONICS AND TELECOMMUNICATIONS'), ('eee', 'ELECTRICAL AND ELCETRONICS ENGINEERING'), ('mech', 'MECHANICAL ENGINEERING'), ('civil', 'CIVIL ENGINEERING')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='libcard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1', '1st SEMESTER'), ('2', '2nd SEMESTER'), ('3', '3rd SEMESTER'), ('4', '4th SEMESTER'), ('5', '5th SEMESTER'), ('6', '6th SEMESTER'), ('7', '7th SEMESTER'), ('8', '8th SEMESTER')], max_length=1, null=True),
        ),
    ]
