# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
