# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_semester'),
        ('users', '0009_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Semester'),
        ),
    ]
