# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
    ]
