# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_student_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='entity',
            field=models.CharField(choices=[('student', 'STUDENT'), ('staff', 'STAFF')], default='student', max_length=100),
        ),
    ]
